CREATE DATABASE test_db;

\connect test_db

CREATE TABLE test_table (
  id INT GENERATED BY DEFAULT AS IDENTITY,
  first_name TEXT,
  last_name TEXT,
  CONSTRAINT pk_test_table PRIMARY KEY (id)
);

CREATE PUBLICATION test_publication FOR ALL TABLES WITH (publish = 'insert, update, delete');
