services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    hostname: rabbitmq  # needed to use the same folder in the volume
    ports:
      - "5672:5672"     # AMQP (default RabbitMQ port)
      - "15672:15672"   # Management UI
      - "5552:5552"     # Streams plugin port
    environment:
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: "-rabbitmq_stream advertised_host localhost"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - ./rabbitmq-config:/etc/rabbitmq
    restart: unless-stopped

volumes:
  rabbitmq_data:
    name: pg2j_rabbitmq_data